release-gem-steps: &release-gem-steps
  - checkout
  - restore_cache:
      keys:
        - v1-ruby-${FEDERALIST_THEME}-{{ checksum "Gemfile.lock" }}
        - v1-ruby-${FEDERALIST_THEME}-
        - v1-ruby-
  - run:
      name: Install Ruby dependencies
      command: bundle install --path vendor/bundle
  - save_cache:
      key: v1-ruby-${FEDERALIST_THEME}-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  - restore_cache:
      keys:
        - v1-npm-${FEDERALIST_THEME}-{{ checksum "package-lock.json" }}
        - v1-npm-${FEDERALIST_THEME}-
        - v1-npm-
  - run:
      name: Install Node.js dependencies
      command: npm install
  - save_cache:
      key: v1-npm-${FEDERALIST_THEME}-{{ checksum "package-lock.json" }}
      paths:
        - node_modules
  - run:
      name: Setup rubygems
      command: .circleci/setup-rubygems.sh
  - run:
      name: Build the theme
      command: npm run build
  - run:
      name: Build gem
      command: |
        cd ${FEDERALIST_THEME}
        npm run gem:build
  - run:
      name: Release gem
      command: |
        cd ${FEDERALIST_THEME}
        npm run gem:release



version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout
      - restore_cache:
          key: v1-ruby-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-ruby-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node.js dependencies
          command: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run setup
      - run: npm run build
      - run: npm test

  release-gem-standard:
    docker:
      - image: circleci/ruby:2.6-node
    environment:
      FEDERALIST_THEME: federalist-standard-theme
    steps: *release-gem-steps


workflows:
  version: 2
  commit:
    jobs:
      - test
      - release-gem-standard:
          requires:
            - test
          filters:
            tags:
              only: /^federalist-standard-theme-v.*/
            branches:
              only: federalist-standard-theme
